### ISSUE TITLE
support for`tags` param in `google_maps_photos`

### ISSUE THREAD

**Issue by sbendary25** [outscraper/outscraper-python#12]
https://github.com/outscraper/outscraper-python/blob/c531f9a4d9ae0bbd29067fc93d68bbd763657c39/outscraper/api_client.py#L437-L439

api docs reference a `tag` query parameter to filter by photo type. can this support be added to this package

**Comment by vlad-stack** [comment]
Added in https://github.com/outscraper/outscraper-python/releases/tag/v5.1.0
