### ISSUE TITLE
Amazon products isn't implemented

### ISSUE THREAD

**Issue by ivoytov** [outscraper/outscraper-python#8]
Documentation says Amazon Products is implemented but it's still missing. Should update documentation to remove mention of this API unless it's available somewhere. I'm using `outscraper-3.0.2-py3-none-any.whl` version.

```
from outscraper import ApiClient

api_client = ApiClient(api_key='api-key')
results = api_client.amazon_products('https://www.amazon.com/dp/B00G3XWLR8', limit=3)
>>> AttributeError: 'ApiClient' object has no attribute 'amazon_products'
```

**Comment by vlad-stack** [comment]
Hi @ivoytov,

Thank you for the request! Amazon products and reviews are available in v3.0.3.
