### ISSUE TITLE
Balance?

### ISSUE THREAD

**Issue by FujiwaraChoki** [outscraper/outscraper-python#9]
You need a balance "to prevent spam"?
Lmao.

**Comment by vlad-stack** [comment]
@FujiwaraChoki can you please tel me more about the issue?

**Comment by FujiwaraChoki** [comment]
> @FujiwaraChoki can you please tel me more about the issue?

Sorry for the late response, but I had a question:

Do you guys have a free & reliable version of this tool, or can you recommend any?

**Comment by junaid9211** [comment]
On your [pricing page ](https://outscraper.com/pricing/) of the website, it says that the tool has API access in the free tier. That is very deceptive

**Comment by FujiwaraChoki** [comment]
> On your [pricing page ](https://outscraper.com/pricing/) of the website, it says that the tool has API access in the free tier. That is very deceptive

I agree.

**Comment by vlad-stack** [comment]
Hi @junaid9211,
> On your [pricing page ](https://outscraper.com/pricing/)of the website, it says that the tool has API access in the free tier.
Yes, as it says: "Free Tier - Usage before 500 businesses" It provides 500 places/500 reviews every 30 days. Now can you please elaborate on why it is deceptive?

**Comment by vlad-stack** [comment]
If you are a new user or want to use API, the platform might ask you to deposit a minimum amount of credits. Especially if you created a few accounts from the same email/IP, or you are using disposable emails. This helps us to validate your account and prevent misuse of the free tier.

I hope it does make sense.
Thank you!

**Comment by vlad-stack** [comment]
In case you need to test the API without any commitments (adding payment method or minimal amount of credits), you might consider attending a [test-drive program](https://outscraper.com/test-drive/).
